### ISSUE TITLE
Compatibility Error on current production branch

### ISSUE THREAD

**Issue by jdgcoop** [davelens/fvtt-party-resources#15]
fvtt-party-resources is showing a compatibility error with the Foundry VTT 0.7.9 production release.  The module appears to still work.

**Comment by ay-vee** [comment]
I have a similar issue, but module doesn't work at all. I've tried uninstalling and installing, but no luck.

**Comment by davelens** [comment]
@jdgcoop That's because the `module.json` file mentions 0.7.8 as the most recent core-compatible version during development of the last update (4 months ago now), but it should work fine. I'm severely delayed with pretty much everything due to COVID-19, but finally have some time planned soon to hopefully get a new release out with a couple of new features.

@ay-vee I run the module in 0.7.9 without issues. Which browser are you using, and are there any errors you can give me to help you along?

**Comment by davelens** [comment]
@jdgcoop A new version was released just now, the compatibility error should be gone now.

@ay-vee Please create a new issue if you're still experiencing problems with the latest version (1.1.4).

**Comment by ay-vee** [comment]
@davelens it works now, thanks!
