### ISSUE TITLE
Resizeable Popup

### ISSUE THREAD

**Issue by Col45** [davelens/fvtt-party-resources#4]
Is it possible to have the popup be resizable so that resources can be viewed horizontally or vertically depending on the popup aspect ratio?

**Comment by davelens** [comment]
@Col45 Probably, yeah. Setting the popup as resizable isn't an issue, but it will probably break how the individual resource blocks behave once resized. I think I have to restyle them to use flexbox instead of CSS grid to make them stack on top of each other when the dashboard is narrow. I'm not a CSS wizard, but I'll see what I can do.

**Comment by davelens** [comment]
@Col45 Resizable dashboard windows will be added in the upcoming 1.1 release. Thank you for the suggestion!

**Comment by Col45** [comment]
Thank you much appreciated! Works like a charm
