### ISSUE TITLE
[Feature Request] Open resource window by clicking/double-clicking on the resource

### ISSUE THREAD

**Issue by jagoe** [davelens/fvtt-party-resources#56]
## Problem

Whenever I want to edit a resource, I have to navigate to the actors tab first. Depending on the frequency, this might get annoying.
Leaving the window open is not option due to limited screen real estate.

## Proposed Solution

Clicking (or double-clicking) on the resource bar opens the "Party Resources" window.

### Alternatives

1. Editing the resource directly using the mouse wheel might also be an option. If both seem like good ideas, I'll open a separate issue.

## Notes

If accepted, I'd be willing to draft a PR.

**Comment by davelens** [comment]
@jagoe In the back of my mind, I think I settled on implementing CTRL+clicking a resource to open the resource's edit form somewhere down the line, but starting out with opening the dashboard when clicking the resource bar itself makes sense to me. 👍

**Comment by davelens** [comment]
@jagoe Merged and released into 1.4.3a. Thanks again, also for the cleanup involving the sass build script. I'm not a frontend dev, so I learned something there. 

I made two changes in addition to yours:

* I added `event.metaKey` as an alternative to `event.ctrlKey` for people running the software on a mac. The latter doesn't seem to allow click events to fire when `ctrl` was pressed. I'm guessing due to a conflicting keybind on macos.
* I added an additional check so only gamemaster level users can access the resource edit form when ctrl+clicking a  resource.

**Comment by jagoe** [comment]
Whoops! Both of those make a lot of sense, haha.
I always forget about Macs (neither me, nor my usual players use one). And I got no excuse for the GM-check - good thing you caught that!

Thanks for the quick review, merge, and release :smiley:

**Comment by jagoe** [comment]
@davelens, just noticed: Foundry doesn't support versions like `1.4.3a`, causing it not to be recognized as the latest version (more details [here](https://foundryvtt.com/article/intro-development/#versioning)).

![image](https://user-images.githubusercontent.com/2989750/203081274-dbb483a6-8d31-407d-8274-63d4b16f2c39.png)

As per [SemVer](https://semver.org) it would have made sense to make the new version `1.5.0` and the hotfix `1.5.1`. As it is, you might want to change `1.4.3a` to `1.4.4` to fix the issue with the latest version.

**Comment by davelens** [comment]
@jagoe Oops, I didn't know that! It's how we do patch releases at work so I didn't really think about it. My self-hosted Foundry seemed to update the version just fine, but not having it as latest isn't good. 1.4.4 is out now to remedy it.

Thanks again for the heads-up!
